# Generated by Django 4.0 on 2023-08-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='youtube_published_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='youtube_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='youtube_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='data',
            name='channel',
        ),
    ]
