# Generated by Django 3.2.9 on 2023-09-21 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_rename_youtube_published_date_data_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='None', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='ranking.book'),
        ),
        migrations.AlterField(
            model_name='data',
            name='published_date',
            field=models.DateField(),
        ),
    ]
