# Generated by Django 3.2.9 on 2023-10-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20230921_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='ranking.channel'),
        ),
    ]
